channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - icu=58
  - python=3
  - r-base=4
  - rdkit
  - python-igraph
  - r-igraph
  - r-doparallel
  - bioconductor-minet
  - bioconductor-biomart
  - r-stringdist
  - r-hmisc
  - r-gplots
  - r-rcpp
  - r-rootsolve
  - r-dtw
  - r-wgcna
  - r-minerva
  - r-combinat
  - r-c3net
  - r-bc3net
  - r-r.utils
  - r-devtools
  - pandas
  - flask
  - requests
  - numpy
  - scipy
  - scikit-learn
  - matplotlib=3.7
  - seaborn
  - tqdm
  - deap
  - r-abind
  - ca-certificates
  - certifi
  - openssl
  - r-plyr
  - jupyterlab
  - r-irkernel
